name: Flutter Analysis
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  package-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@main
        with:
          channel: stable

      - name: install dependencies
        run: flutter pub get

      - name: format code
        run: flutter format --set-exit-if-changed .

      - name: analyze code
        run: flutter analyze .

      - name: run tests
        run: flutter test
